version: '3.9'

services:
  #Backend build
#  api:
#    build: ./Backend

 #   command: python3 manage.py run -h 0.0.0.0
 #   container_name: flask-api
 #   depends_on:
 #     - database
 #   ports:
 #     - 5000:5000
 #   env_file:
 #     - ./Backend/env.dev
   
 #   volumes:
 #       - .:/code



  #DB build
  database:
    
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: VacationIO
    image: 'postgres:latest'
    container_name: VacationIO
    restart: always
    ports:
      - 5432:5432
    volumes:
      #- postgres_data:/var/lib/postgresql/data/
      - ./db-data/:/var/lib/postgresql/data=rwx/

  #Frontend build
 # frontend:
  #  build:
  #    context: ./frontend
  #  ports:
  #    - "3000:3000"
  #  container_name: react-ui
  #  stdin_open: true
  #  volumes:
  #     - ./frontend:/usr/src/frontend
  #     - /usr/src/frontend/node_modules

      
